// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwhKsQ1eLk8lcQBGDi9q8CjS4b9LcAJKg',
    appId: '1:116446859296:web:4f69b142a44655bf0bec45',
    messagingSenderId: '116446859296',
    projectId: 'act13v2',
    authDomain: 'act13v2.firebaseapp.com',
    storageBucket: 'act13v2.firebasestorage.app',
    measurementId: 'G-62Q1RJKM5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDr2-MxtJR7GAHZK4aV-5UUqCmPt9TOdY',
    appId: '1:116446859296:android:5369cf3b7a714dd70bec45',
    messagingSenderId: '116446859296',
    projectId: 'act13v2',
    storageBucket: 'act13v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrjdtOrSHaBKvof5jd6cHm_6fJAfQa9HQ',
    appId: '1:116446859296:ios:d7a39b0df97961930bec45',
    messagingSenderId: '116446859296',
    projectId: 'act13v2',
    storageBucket: 'act13v2.firebasestorage.app',
    iosBundleId: 'com.example.act13v2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrjdtOrSHaBKvof5jd6cHm_6fJAfQa9HQ',
    appId: '1:116446859296:ios:d7a39b0df97961930bec45',
    messagingSenderId: '116446859296',
    projectId: 'act13v2',
    storageBucket: 'act13v2.firebasestorage.app',
    iosBundleId: 'com.example.act13v2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwhKsQ1eLk8lcQBGDi9q8CjS4b9LcAJKg',
    appId: '1:116446859296:web:e7d6cb23f674a0fa0bec45',
    messagingSenderId: '116446859296',
    projectId: 'act13v2',
    authDomain: 'act13v2.firebaseapp.com',
    storageBucket: 'act13v2.firebasestorage.app',
    measurementId: 'G-XGGS0YQ0K4',
  );

}